name: Deploy My Web Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set the PERSONALACCESSTOKEN as an environment variable
      - name: Set Environment Variables
        env:
          PERSONALACCESSTOKEN: ${{ secrets.PERSONALACCESSTOKEN }}
        run: |
          echo "PERSONALACCESSTOKEN=$PERSONALACCESSTOKEN" >> $GITHUB_ENV

      # Run a build or deploy script here if needed
      - name: Build and Deploy
        run: |
          # You can access the PERSONALACCESSTOKEN as $PERSONALACCESSTOKEN here
          echo "Token: $PERSONALACCESSTOKEN"

      # Additional steps for deploying your web page, e.g., copying files, pushing to a hosting service, etc.
